version: "3.8"

services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,cloudfront
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
